name: Danger

on:
  pull_request:
    branches: [ main ]

jobs:
  danger:
    name: 'Danger'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Node
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        gem install danger danger-prose danger-commit_lint
        python -m pip install --upgrade pip
        pip install proselint
        npm i markdown-spellcheck -g
        go get golang.org/x/lint/golint
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: danger
